language: julia
notifications:
  email: false
sudo: required

matrix:
  - include:
    - julia: 1.0
      env:
        - JOBQUEUE=slurm

services: docker
before_install:
  - set -e
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
  - set +e
install:
  - set -e
  - jobqueue_install
  - set +e
script:
  - set -e
  - jobqueue_script
  - set +e
after_script:
  - jobqueue_after_script

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
#after_success:
#  - julia -e 'cd(Pkg.dir("Clustermanagers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
